# Generated by Django 5.2 on 2026-05-29 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Fakultas',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIDN')),
                ('nuptk', models.CharField(blank=True, max_length=30, null=True, verbose_name='NUPTK')),
                ('nip', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='NIP')),
                ('no_ktp', models.CharField(blank=True, max_length=20, null=True, verbose_name='No. KTP')),
                ('karpeg', models.CharField(blank=True, max_length=20, null=True, verbose_name='KARPEG')),
                ('nira', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIRA')),
                ('no_reg_serdos', models.CharField(blank=True, max_length=30, null=True, verbose_name='No. Reg. Serdos')),
                ('nama_lengkap', models.CharField(max_length=200, verbose_name='Nama Lengkap (dengan gelar)')),
                ('nama_terang', models.CharField(max_length=200, verbose_name='Nama Terang (tanpa gelar)')),
                ('gelar_depan', models.CharField(blank=True, max_length=100, verbose_name='Gelar Depan')),
                ('gelar_belakang', models.CharField(blank=True, max_length=100, verbose_name='Gelar Belakang')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('agama', models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Hindu', 'Hindu'), ('Budha', 'Budha'), ('Konghucu', 'Konghucu')], max_length=20)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('jurusan_bagian', models.CharField(blank=True, max_length=200, verbose_name='Jurusan/Bagian')),
                ('program_studi_nama', models.CharField(blank=True, max_length=200, verbose_name='Program Studi')),
                ('jenjang_prodi', models.CharField(blank=True, max_length=10, verbose_name='Jenjang Prodi')),
                ('status', models.CharField(choices=[('PNS', 'PNS'), ('CPNS', 'CPNS'), ('PPPK', 'PPPK'), ('Non-PNS', 'Non-PNS')], default='PNS', max_length=20)),
                ('tmt_cpns', models.DateField(blank=True, null=True, verbose_name='TMT CPNS')),
                ('tmt_pns', models.DateField(blank=True, null=True, verbose_name='TMT PNS')),
                ('ranting_ilmu', models.CharField(blank=True, max_length=300, verbose_name='Ranting Ilmu/Kepakaran')),
                ('tingkat_ijazah_bkn', models.CharField(blank=True, max_length=10, verbose_name='Tingkat Ijazah BKN')),
                ('tingkat_ijazah_borang', models.CharField(blank=True, max_length=10, verbose_name='Tingkat Ijazah Borang')),
                ('usia_pensiun', models.IntegerField(blank=True, null=True, verbose_name='Usia Pensiun')),
                ('tahun_pensiun', models.IntegerField(blank=True, null=True, verbose_name='Tahun Pensiun')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosen_created', to=settings.AUTH_USER_MODEL)),
                ('fakultas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosen', to='dosen.fakultas')),
            ],
            options={
                'verbose_name_plural': 'Dosen',
                'ordering': ['nama_lengkap'],
            },
        ),
        migrations.CreateModel(
            name='MasaKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpns_tahun', models.IntegerField(blank=True, null=True)),
                ('cpns_bulan', models.IntegerField(blank=True, null=True)),
                ('golongan_tahun', models.IntegerField(blank=True, null=True)),
                ('golongan_bulan', models.IntegerField(blank=True, null=True)),
                ('jabatan_tahun', models.IntegerField(blank=True, null=True)),
                ('jabatan_bulan', models.IntegerField(blank=True, null=True)),
                ('keseluruhan_tahun', models.IntegerField(blank=True, null=True)),
                ('keseluruhan_bulan', models.IntegerField(blank=True, null=True)),
                ('pensiun_tahun', models.IntegerField(blank=True, null=True)),
                ('pensiun_bulan', models.IntegerField(blank=True, null=True)),
                ('tanggal_update', models.DateField(auto_now=True)),
                ('dosen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='masa_kerja', to='dosen.dosen')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('jenjang', models.CharField(blank=True, max_length=10)),
                ('fakultas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_studi', to='dosen.fakultas')),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatJabatanFungsional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenjang', models.CharField(max_length=100)),
                ('tmt', models.DateField()),
                ('angka_kredit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_jabatan_fungsional', to='dosen.dosen')),
            ],
            options={
                'ordering': ['-tmt'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatKepangkatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pangkat', models.CharField(max_length=100)),
                ('golongan', models.CharField(max_length=10)),
                ('tmt', models.DateField()),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_kepangkatan', to='dosen.dosen')),
            ],
            options={
                'ordering': ['-tmt'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatPendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenjang', models.CharField(max_length=10)),
                ('bidang_studi', models.CharField(blank=True, max_length=200)),
                ('institusi', models.CharField(blank=True, max_length=200)),
                ('tahun_lulus', models.IntegerField(blank=True, null=True)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_pendidikan', to='dosen.dosen')),
            ],
            options={
                'ordering': ['-jenjang'],
            },
        ),
        migrations.CreateModel(
            name='TugasTambahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=200)),
                ('no_sk', models.CharField(blank=True, max_length=100)),
                ('tgl_sk', models.DateField(blank=True, null=True)),
                ('tmt_jabatan', models.DateField(blank=True, null=True)),
                ('is_aktif', models.BooleanField(default=True)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas_tambahan', to='dosen.dosen')),
            ],
            options={
                'ordering': ['-tmt_jabatan'],
            },
        ),
    ]
