# Generated by Django 4.2.21 on 2026-06-16 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatStatusDosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AKTIF', 'Aktif'), ('CUTI', 'Cuti'), ('TUGAS_BELAJAR', 'Tugas Belajar'), ('IZIN_BELAJAR', 'Izin Belajar'), ('CLTN', 'CLTN'), ('PENSIUN', 'Pensiun'), ('MENINGGAL', 'Meninggal'), ('PINDAH', 'Pindah Instansi'), ('BERHENTI', 'Berhenti')], max_length=30)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_akhir', models.DateField(blank=True, null=True)),
                ('no_sk', models.CharField(blank=True, max_length=100)),
                ('keterangan', models.TextField(blank=True)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_status', to='dosen.dosen')),
            ],
        ),
    ]
