# Generated by Django 5.2 on 2026-07-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0002_riwayatstatusdosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatstatusdosen',
            name='jenis_cuti',
            field=models.CharField(blank=True, choices=[('TAHUNAN', 'Cuti Tahunan'), ('BESAR', 'Cuti Besar'), ('SAKIT', 'Cuti Sakit'), ('MELAHIRKAN', 'Cuti Melahirkan'), ('ALASAN_PENTING', 'Cuti Karena Alasan Penting'), ('DILUAR_TANGGUNGAN_NEGARA', 'Cuti di Luar Tanggungan Negara')], max_length=50, null=True),
        ),
    ]
