# Generated by Django 5.2 on 2026-07-16 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0003_riwayatstatusdosen_jenis_cuti'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeluargaDosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('status_hubungan', models.CharField(choices=[('SUAMI', 'Suami'), ('ISTRI', 'Istri'), ('ANAK', 'Anak')], max_length=20)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('pekerjaan', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keluarga', to='dosen.dosen')),
            ],
            options={
                'ordering': ['status_hubungan', 'tanggal_lahir'],
            },
        ),
    ]
