# Generated by Django 5.2 on 2026-07-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0004_keluargadosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='keluargadosen',
            name='dokumen_pendukung',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Dokumen Pendukung (Link)'),
        ),
        migrations.AddField(
            model_name='riwayatjabatanfungsional',
            name='dokumen_pendukung',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Dokumen Pendukung (Link)'),
        ),
        migrations.AddField(
            model_name='riwayatkepangkatan',
            name='dokumen_pendukung',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Dokumen Pendukung (Link)'),
        ),
        migrations.AddField(
            model_name='riwayatpendidikan',
            name='dokumen_pendukung',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Dokumen Pendukung (Link)'),
        ),
        migrations.AddField(
            model_name='riwayatstatusdosen',
            name='dokumen_pendukung',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Dokumen Pendukung (Link)'),
        ),
        migrations.AddField(
            model_name='tugastambahan',
            name='dokumen_pendukung',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Dokumen Pendukung (Link)'),
        ),
    ]
