# Generated by Django 4.2.30 on 2026-07-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0004_keluargadosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='tmt_pensiun',
            field=models.DateField(blank=True, null=True, verbose_name='TMT Pensiun (BUP)'),
        ),
    ]
