# Generated by Django 4.2.30 on 2026-07-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0005_dosen_tmt_pensiun'),
        ('dosen', '0005_keluargadosen_dokumen_pendukung_and_more'),
    ]

    operations = [
    ]
