# Generated by Django 5.2 on 2026-05-30 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dosen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIDN/NI')),
                ('nuptk', models.CharField(blank=True, max_length=30, null=True, verbose_name='NUPTK')),
                ('nip', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='NIP')),
                ('no_ktp', models.CharField(blank=True, max_length=20, null=True, verbose_name='No. KTP')),
                ('karpeg', models.CharField(blank=True, max_length=20, null=True, verbose_name='KARPEG')),
                ('nira', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIRA')),
                ('nama_lengkap', models.CharField(max_length=200, verbose_name='Nama Lengkap (dengan gelar)')),
                ('nama_terang', models.CharField(max_length=200, verbose_name='Nama Terang (tanpa gelar)')),
                ('gelar_depan', models.CharField(blank=True, max_length=100, verbose_name='Gelar Depan')),
                ('gelar_belakang', models.CharField(blank=True, max_length=100, verbose_name='Gelar Belakang')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('agama', models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Hindu', 'Hindu'), ('Budha', 'Budha'), ('Konghucu', 'Konghucu')], max_length=20)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('bagian', models.CharField(blank=True, max_length=200, verbose_name='Bagian/Sub-Bagian')),
                ('status', models.CharField(choices=[('PNS', 'PNS'), ('CPNS', 'CPNS'), ('PPPK', 'PPPK'), ('Non-PNS', 'Non-PNS')], default='PNS', max_length=20)),
                ('tmt_cpns', models.DateField(blank=True, null=True, verbose_name='TMT CPNS')),
                ('tmt_pns', models.DateField(blank=True, null=True, verbose_name='TMT PNS')),
                ('bidang_keahlian', models.CharField(blank=True, max_length=300, verbose_name='Bidang Keahlian')),
                ('tingkat_ijazah_bkn', models.CharField(blank=True, max_length=10, verbose_name='Tingkat Ijazah BKN')),
                ('tingkat_ijazah_borang', models.CharField(blank=True, max_length=10, verbose_name='Tingkat Ijazah Borang')),
                ('usia_pensiun', models.IntegerField(blank=True, null=True, verbose_name='Usia Pensiun')),
                ('tahun_pensiun', models.IntegerField(blank=True, null=True, verbose_name='Tahun Pensiun')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tendik_created', to=settings.AUTH_USER_MODEL)),
                ('fakultas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tendik', to='dosen.fakultas', verbose_name='Fakultas (jika di Fakultas)')),
            ],
            options={
                'verbose_name': 'Tenaga Kependidikan',
                'verbose_name_plural': 'Tenaga Kependidikan',
                'ordering': ['nama_lengkap'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatPendidikanTendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenjang', models.CharField(max_length=10)),
                ('bidang_studi', models.CharField(blank=True, max_length=200)),
                ('institusi', models.CharField(blank=True, max_length=200)),
                ('tahun_lulus', models.IntegerField(blank=True, null=True)),
                ('tendik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_pendidikan', to='tendik.tendik')),
            ],
            options={
                'verbose_name': 'Riwayat Pendidikan Tendik',
                'ordering': ['-jenjang'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatKepangkatanTendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pangkat', models.CharField(max_length=100)),
                ('golongan', models.CharField(max_length=10)),
                ('tmt', models.DateField()),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tendik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_kepangkatan', to='tendik.tendik')),
            ],
            options={
                'verbose_name': 'Riwayat Kepangkatan Tendik',
                'ordering': ['-tmt'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatJabatanFungsionalTendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenjang', models.CharField(max_length=100)),
                ('tmt', models.DateField()),
                ('angka_kredit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tendik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_jabatan_fungsional', to='tendik.tendik')),
            ],
            options={
                'verbose_name': 'Riwayat Jabatan Fungsional Tendik',
                'ordering': ['-tmt'],
            },
        ),
        migrations.CreateModel(
            name='MasaKerjaTendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpns_tahun', models.IntegerField(blank=True, null=True)),
                ('cpns_bulan', models.IntegerField(blank=True, null=True)),
                ('golongan_tahun', models.IntegerField(blank=True, null=True)),
                ('golongan_bulan', models.IntegerField(blank=True, null=True)),
                ('jabatan_tahun', models.IntegerField(blank=True, null=True)),
                ('jabatan_bulan', models.IntegerField(blank=True, null=True)),
                ('keseluruhan_tahun', models.IntegerField(blank=True, null=True)),
                ('keseluruhan_bulan', models.IntegerField(blank=True, null=True)),
                ('pensiun_tahun', models.IntegerField(blank=True, null=True)),
                ('pensiun_bulan', models.IntegerField(blank=True, null=True)),
                ('tanggal_update', models.DateField(auto_now=True)),
                ('tendik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='masa_kerja', to='tendik.tendik')),
            ],
            options={
                'verbose_name': 'Masa Kerja Tendik',
            },
        ),
        migrations.CreateModel(
            name='JabatanStrukturalTendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=200, verbose_name='Jabatan Struktural')),
                ('eselon', models.CharField(blank=True, choices=[('II/a', 'II/a'), ('II/b', 'II/b'), ('III/a', 'III/a'), ('III/b', 'III/b'), ('IV/a', 'IV/a'), ('IV/b', 'IV/b'), ('Pelaksana', 'Pelaksana')], max_length=10, verbose_name='Eselon')),
                ('unit_kerja', models.CharField(blank=True, max_length=200, verbose_name='Unit Kerja Jabatan')),
                ('no_sk', models.CharField(blank=True, max_length=100)),
                ('tgl_sk', models.DateField(blank=True, null=True)),
                ('tmt_jabatan', models.DateField(blank=True, null=True)),
                ('is_aktif', models.BooleanField(default=True)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tendik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jabatan_struktural', to='tendik.tendik')),
            ],
            options={
                'verbose_name': 'Jabatan Struktural Tendik',
                'ordering': ['-tmt_jabatan'],
            },
        ),
        migrations.CreateModel(
            name='TugasTambahanTendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=200)),
                ('no_sk', models.CharField(blank=True, max_length=100)),
                ('tgl_sk', models.DateField(blank=True, null=True)),
                ('tmt_jabatan', models.DateField(blank=True, null=True)),
                ('is_aktif', models.BooleanField(default=True)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tendik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas_tambahan', to='tendik.tendik')),
            ],
            options={
                'verbose_name': 'Tugas Tambahan Tendik',
                'ordering': ['-tmt_jabatan'],
            },
        ),
        migrations.CreateModel(
            name='UnitKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=200)),
                ('jenis', models.CharField(choices=[('REKTORAT', 'Rektorat'), ('BIRO', 'Biro'), ('BAGIAN', 'Bagian'), ('SUB_BAGIAN', 'Sub-Bagian'), ('UPT', 'UPT'), ('FAKULTAS', 'Fakultas'), ('LEMBAGA', 'Lembaga'), ('LAINNYA', 'Lainnya')], default='BAGIAN', max_length=30)),
                ('induk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_unit', to='tendik.unitkerja', verbose_name='Unit Induk')),
            ],
            options={
                'verbose_name': 'Unit Kerja',
                'verbose_name_plural': 'Unit Kerja',
                'ordering': ['nama'],
            },
        ),
        migrations.AddField(
            model_name='tendik',
            name='unit_kerja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tendik', to='tendik.unitkerja', verbose_name='Unit Kerja'),
        ),
    ]
