# Generated by Django 4.2.21 on 2026-06-11 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tendik',
            name='nidn',
        ),
        migrations.RemoveField(
            model_name='tendik',
            name='nuptk',
        ),
        migrations.AddField(
            model_name='jabatanstrukturaltendik',
            name='jenjang',
            field=models.CharField(blank=True, max_length=100, verbose_name='Jenjang (misal: Kepala Biro)'),
        ),
        migrations.AddField(
            model_name='riwayatjabatanfungsionaltendik',
            name='jenis',
            field=models.CharField(choices=[('FUNGSIONAL_TERTENTU', 'Fungsional Tertentu'), ('FUNGSIONAL_UMUM', 'Fungsional Umum')], default='FUNGSIONAL_TERTENTU', max_length=30),
        ),
        migrations.AddField(
            model_name='riwayatjabatanfungsionaltendik',
            name='nama_jabatan',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nama Jabatan'),
        ),
        migrations.AddField(
            model_name='riwayatpendidikantendik',
            name='fakultas_pt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fakultas PT'),
        ),
        migrations.AddField(
            model_name='riwayatpendidikantendik',
            name='prodi_pddikti',
            field=models.CharField(blank=True, max_length=200, verbose_name='Prodi PDDikti'),
        ),
        migrations.AddField(
            model_name='tendik',
            name='alamat',
            field=models.TextField(blank=True, verbose_name='Alamat Lengkap'),
        ),
        migrations.AddField(
            model_name='tendik',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='tendik',
            name='no_hp',
            field=models.CharField(blank=True, max_length=20, verbose_name='No. HP'),
        ),
        migrations.AddField(
            model_name='tendik',
            name='tingkat_ijazah_profesi',
            field=models.BooleanField(default=False, verbose_name='Memiliki Profesi'),
        ),
        migrations.AddField(
            model_name='tendik',
            name='tmt_kgb',
            field=models.DateField(blank=True, null=True, verbose_name='TMT Kenaikan Gaji Berkala'),
        ),
        migrations.AddField(
            model_name='tendik',
            name='tmt_pensiun',
            field=models.DateField(blank=True, null=True, verbose_name='TMT Pensiun'),
        ),
        migrations.AlterField(
            model_name='jabatanstrukturaltendik',
            name='eselon',
            field=models.CharField(blank=True, choices=[('II/a', 'II/a'), ('II/b', 'II/b'), ('III/a', 'III/a'), ('III/b', 'III/b'), ('IV/a', 'IV/a'), ('IV/b', 'IV/b'), ('Pelaksana', 'Pelaksana')], max_length=10),
        ),
        migrations.AlterField(
            model_name='jabatanstrukturaltendik',
            name='jabatan',
            field=models.CharField(max_length=200, verbose_name='Nama Jabatan'),
        ),
        migrations.AlterField(
            model_name='jabatanstrukturaltendik',
            name='unit_kerja',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='riwayatjabatanfungsionaltendik',
            name='jenjang',
            field=models.CharField(blank=True, choices=[('Ahli Utama', 'Ahli Utama'), ('Ahli Madya', 'Ahli Madya'), ('Ahli Muda', 'Ahli Muda'), ('Ahli Pertama', 'Ahli Pertama'), ('Penyelia', 'Penyelia'), ('Mahir', 'Mahir'), ('Terampil', 'Terampil'), ('Pelaksana Lanjutan', 'Pelaksana Lanjutan'), ('Pelaksana', 'Pelaksana')], max_length=50),
        ),
        migrations.AlterField(
            model_name='riwayatkepangkatantendik',
            name='pangkat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='riwayatpendidikantendik',
            name='bidang_studi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Program Studi'),
        ),
        migrations.AlterField(
            model_name='riwayatpendidikantendik',
            name='institusi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Universitas'),
        ),
        migrations.AlterField(
            model_name='riwayatpendidikantendik',
            name='jenjang',
            field=models.CharField(choices=[('SD', 'SD'), ('SLTP', 'SLTP'), ('SLTA', 'SLTA'), ('D3', 'D3'), ('D4', 'D4'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('PROFESI', 'Profesi')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tendik',
            name='bidang_keahlian',
            field=models.CharField(blank=True, max_length=300, verbose_name='Ranting Ilmu / Kepakaran'),
        ),
        migrations.AlterField(
            model_name='tendik',
            name='nama_terang',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nama Terang (tanpa gelar)'),
        ),
        migrations.AlterField(
            model_name='tendik',
            name='no_ktp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No. KTP / NIK'),
        ),
        migrations.AlterField(
            model_name='tendik',
            name='status',
            field=models.CharField(choices=[('PNS', 'PNS'), ('CPNS', 'CPNS'), ('PPPK', 'PPPK'), ('PTT', 'PTT')], default='PNS', max_length=20),
        ),
        migrations.AlterField(
            model_name='tendik',
            name='tingkat_ijazah_bkn',
            field=models.CharField(blank=True, choices=[('SD', 'SD'), ('SLTP', 'SLTP'), ('SLTA', 'SLTA'), ('D3', 'D3'), ('D4', 'D4'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('PROFESI', 'Profesi')], max_length=10, verbose_name='Tingkat Ijazah BKN'),
        ),
        migrations.AlterField(
            model_name='unitkerja',
            name='jenis',
            field=models.CharField(choices=[('REKTORAT', 'Rektorat'), ('BIRO', 'Biro'), ('BAGIAN', 'Bagian'), ('SUB_BAGIAN', 'Sub-Bagian'), ('UPT', 'UPT'), ('UPA', 'UPA'), ('FAKULTAS', 'Fakultas'), ('LEMBAGA', 'Lembaga'), ('RS', 'Rumah Sakit'), ('PASCASARJANA', 'Pascasarjana'), ('LAINNYA', 'Lainnya')], default='BAGIAN', max_length=30),
        ),
        migrations.CreateModel(
            name='RiwayatBerhentiTendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alasan', models.CharField(choices=[('PENSIUN', 'Pensiun'), ('PENSIUN_DINI', 'Pensiun Dini'), ('MENINGGAL', 'Meninggal Dunia'), ('PINDAH', 'Pindah Instansi'), ('DIBERHENTIKAN', 'Diberhentikan'), ('LAINNYA', 'Lainnya')], max_length=30)),
                ('tanggal', models.DateField(verbose_name='Tanggal Berhenti / Meninggal')),
                ('no_sk', models.CharField(blank=True, max_length=100)),
                ('no_telp_keluarga', models.CharField(blank=True, max_length=30, verbose_name='No. Telp Keluarga')),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tendik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_berhenti', to='tendik.tendik')),
            ],
            options={
                'verbose_name': 'Riwayat Berhenti Tendik',
            },
        ),
        migrations.CreateModel(
            name='ReferensiJabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('STRUKTURAL', 'Struktural'), ('FUNGSIONAL_TERTENTU', 'Fungsional Tertentu'), ('FUNGSIONAL_UMUM', 'Fungsional Umum'), ('PPPK', 'PPPK')], max_length=30)),
                ('nama_jabatan', models.CharField(max_length=200, verbose_name='Nama Jabatan')),
                ('id_grade', models.IntegerField(blank=True, null=True, verbose_name='ID Grade (PPPK)')),
                ('kelas_jabatan', models.IntegerField(blank=True, null=True, verbose_name='Kelas Jabatan')),
                ('nominal_gaji', models.BigIntegerField(blank=True, null=True, verbose_name='Nominal Gaji (Rp)')),
            ],
            options={
                'verbose_name': 'Referensi Jabatan',
                'ordering': ['jenis', 'nama_jabatan'],
                'unique_together': {('jenis', 'nama_jabatan')},
            },
        ),
        migrations.CreateModel(
            name='DetailPPPK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmt_pppk', models.DateField(blank=True, null=True, verbose_name='TMT PPPK')),
                ('tmt_berkala', models.DateField(blank=True, null=True, verbose_name='TMT Berkala')),
                ('thn_pengangkatan', models.IntegerField(blank=True, null=True, verbose_name='Tahun Pengangkatan')),
                ('thn_berjalan', models.IntegerField(blank=True, null=True, verbose_name='Tahun Berjalan Kontrak')),
                ('sisa_masa_kerja', models.CharField(blank=True, max_length=100, verbose_name='Sisa Masa Kerja (teks)')),
                ('tendik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pppk', to='tendik.tendik')),
            ],
            options={
                'verbose_name': 'Detail PPPK',
            },
        ),
        migrations.CreateModel(
            name='CutiTendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_cuti', models.CharField(choices=[('TAHUNAN', 'Cuti Tahunan'), ('SAKIT', 'Cuti Sakit'), ('MELAHIRKAN', 'Cuti Melahirkan'), ('ALASAN_PENTING', 'Cuti Alasan Penting'), ('BESAR', 'Cuti Besar'), ('LUAR_TANGGUNGAN', 'Cuti Di Luar Tanggungan Negara'), ('IZIN', 'Izin')], default='TAHUNAN', max_length=30)),
                ('alasan', models.CharField(blank=True, max_length=200)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_akhir', models.DateField()),
                ('lama_hari_kerja', models.IntegerField(blank=True, null=True, verbose_name='Lama (Hari Kerja)')),
                ('no_sk', models.CharField(blank=True, max_length=100)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tendik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_cuti', to='tendik.tendik')),
            ],
            options={
                'verbose_name': 'Cuti Tendik',
                'verbose_name_plural': 'Cuti Tendik',
                'ordering': ['-tanggal_mulai'],
            },
        ),
    ]
