# Generated by Django 4.2.21 on 2026-06-12 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0001_initial'),
        ('tendik', '0002_remove_tendik_nidn_remove_tendik_nuptk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tendik',
            options={'ordering': ['nama_terang'], 'verbose_name': 'Tenaga Kependidikan', 'verbose_name_plural': 'Tenaga Kependidikan'},
        ),
        migrations.RemoveField(
            model_name='detailpppk',
            name='sisa_masa_kerja',
        ),
        migrations.RemoveField(
            model_name='tendik',
            name='nama_lengkap',
        ),
        migrations.RemoveField(
            model_name='tendik',
            name='tahun_pensiun',
        ),
        migrations.RemoveField(
            model_name='tendik',
            name='tmt_pensiun',
        ),
        migrations.AddField(
            model_name='tendik',
            name='nidn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIDN/NI'),
        ),
        migrations.AddField(
            model_name='tendik',
            name='nuptk',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='NUPTK'),
        ),
        migrations.AlterField(
            model_name='jabatanstrukturaltendik',
            name='eselon',
            field=models.CharField(blank=True, choices=[('II/a', 'II/a'), ('II/b', 'II/b'), ('III/a', 'III/a'), ('III/b', 'III/b'), ('IV/a', 'IV/a'), ('IV/b', 'IV/b'), ('Pelaksana', 'Pelaksana')], max_length=10, verbose_name='Eselon'),
        ),
        migrations.AlterField(
            model_name='jabatanstrukturaltendik',
            name='jabatan',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jabatanstrukturaltendik',
            name='jenjang',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='referensijabatan',
            name='jenis',
            field=models.CharField(choices=[('STRUKTURAL', 'Struktural'), ('FUNGSIONAL_TERTENTU', 'Fungsional Tertentu'), ('FUNGSIONAL_UMUM', 'Fungsional Umum / Pelaksana')], max_length=30),
        ),
        migrations.AlterField(
            model_name='referensijabatan',
            name='kelas_jabatan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referensijabatan',
            name='nama_jabatan',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='riwayatberhentitendik',
            name='tanggal',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='riwayatjabatanfungsionaltendik',
            name='jenis',
            field=models.CharField(choices=[('FUNGSIONAL_TERTENTU', 'Fungsional Tertentu'), ('FUNGSIONAL_UMUM', 'Fungsional Umum / Pelaksana')], default='FUNGSIONAL_TERTENTU', max_length=30),
        ),
        migrations.AlterField(
            model_name='tendik',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tendik',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='tendik',
            name='fakultas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tendik', to='dosen.fakultas', verbose_name='Fakultas'),
        ),
        migrations.AlterField(
            model_name='tendik',
            name='nama_terang',
            field=models.CharField(max_length=200, verbose_name='Nama Terang (tanpa gelar)'),
        ),
        migrations.AlterField(
            model_name='tendik',
            name='tingkat_ijazah_profesi',
            field=models.BooleanField(default=False, verbose_name='Memiliki Ijazah Profesi'),
        ),
        migrations.AlterField(
            model_name='tendik',
            name='usia_pensiun',
            field=models.IntegerField(blank=True, default=60, null=True, verbose_name='Usia Pensiun'),
        ),
        migrations.DeleteModel(
            name='MasaKerjaTendik',
        ),
    ]
