# Generated by Django 4.2.21 on 2026-06-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0003_alter_tendik_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tendik',
            name='nidn',
        ),
    ]
