# Generated by Django 4.2.21 on 2026-06-12 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0004_remove_tendik_nidn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tendik',
            name='karpeg',
        ),
        migrations.RemoveField(
            model_name='tendik',
            name='nira',
        ),
    ]
