# Generated by Django 4.2.21 on 2026-06-12 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0005_remove_tendik_karpeg_remove_tendik_nira'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tendik',
            name='fakultas',
        ),
        migrations.RemoveField(
            model_name='unitkerja',
            name='induk',
        ),
        migrations.RemoveField(
            model_name='unitkerja',
            name='jenis',
        ),
    ]
