# Generated by Django 4.2.21 on 2026-06-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0006_remove_tendik_fakultas_remove_unitkerja_induk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tendik',
            name='tmt_cpns',
        ),
    ]
