# Generated by Django 4.2.21 on 2026-06-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0007_remove_tendik_tmt_cpns'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendik',
            name='mk_cpns_bulan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Masa Kerja CPNS (Bulan)'),
        ),
        migrations.AddField(
            model_name='tendik',
            name='mk_cpns_tahun',
            field=models.IntegerField(blank=True, null=True, verbose_name='Masa Kerja CPNS (Tahun)'),
        ),
    ]
