# Generated by Django 5.2 on 2026-07-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0008_tendik_mk_cpns_bulan_tendik_mk_cpns_tahun'),
    ]

    operations = [
        migrations.AddField(
            model_name='jabatanstrukturaltendik',
            name='dokumen_pendukung',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Dokumen Pendukung (Link)'),
        ),
        migrations.AddField(
            model_name='riwayatberhentitendik',
            name='dokumen_pendukung',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Dokumen Pendukung (Link)'),
        ),
        migrations.AddField(
            model_name='riwayatjabatanfungsionaltendik',
            name='dokumen_pendukung',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Dokumen Pendukung (Link)'),
        ),
        migrations.AddField(
            model_name='riwayatkepangkatantendik',
            name='dokumen_pendukung',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Dokumen Pendukung (Link)'),
        ),
        migrations.AddField(
            model_name='riwayatpendidikantendik',
            name='dokumen_pendukung',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Dokumen Pendukung (Link)'),
        ),
        migrations.AddField(
            model_name='tugastambahantendik',
            name='dokumen_pendukung',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Dokumen Pendukung (Link)'),
        ),
    ]
