# Generated by Django 4.2.30 on 2026-07-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0008_tendik_mk_cpns_bulan_tendik_mk_cpns_tahun'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendik',
            name='tmt_pensiun',
            field=models.DateField(blank=True, null=True, verbose_name='TMT Pensiun'),
        ),
        migrations.AlterField(
            model_name='tendik',
            name='usia_pensiun',
            field=models.IntegerField(blank=True, default=58, null=True, verbose_name='Usia Pensiun'),
        ),
    ]
