# Generated by Django 4.2.30 on 2026-07-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0009_tendik_tmt_pensiun_alter_tendik_usia_pensiun'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatStatusTendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AKTIF', 'Aktif'), ('CUTI', 'Cuti'), ('TUGAS_BELAJAR', 'Tugas Belajar'), ('IZIN_BELAJAR', 'Izin Belajar'), ('CLTN', 'CLTN')], max_length=30)),
                ('jenis_cuti', models.CharField(blank=True, choices=[('TAHUNAN', 'Cuti Tahunan'), ('SAKIT', 'Cuti Sakit'), ('MELAHIRKAN', 'Cuti Melahirkan'), ('ALASAN_PENTING', 'Cuti Alasan Penting'), ('BESAR', 'Cuti Besar'), ('LUAR_TANGGUNGAN', 'Cuti Di Luar Tanggungan Negara'), ('IZIN', 'Izin')], max_length=30, null=True, verbose_name='Jenis Cuti')),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_akhir', models.DateField(blank=True, null=True)),
                ('no_sk', models.CharField(blank=True, max_length=100)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tendik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_status', to='tendik.tendik')),
            ],
            options={
                'verbose_name': 'Riwayat Status Tendik',
                'verbose_name_plural': 'Riwayat Status Tendik',
                'ordering': ['-tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='KeluargaTendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('status_hubungan', models.CharField(choices=[('SUAMI', 'Suami'), ('ISTRI', 'Istri'), ('ANAK', 'Anak')], max_length=20)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('pekerjaan', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tendik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keluarga', to='tendik.tendik')),
            ],
            options={
                'verbose_name': 'Keluarga Tendik',
                'verbose_name_plural': 'Keluarga Tendik',
                'ordering': ['status_hubungan', 'tanggal_lahir'],
            },
        ),
    ]
