# Generated by Django 5.2 on 2026-07-24 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0009_jabatanstrukturaltendik_dokumen_pendukung_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeluargaDosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('status_hubungan', models.CharField(choices=[('SUAMI', 'Suami'), ('ISTRI', 'Istri'), ('ANAK', 'Anak')], max_length=20)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('pekerjaan', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dokumen_pendukung', models.URLField(blank=True, max_length=500, null=True, verbose_name='Dokumen Pendukung (Link)')),
                ('tendik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keluarga', to='tendik.tendik')),
            ],
            options={
                'ordering': ['status_hubungan', 'tanggal_lahir'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatStatusTendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AKTIF', 'Aktif'), ('CUTI', 'Cuti'), ('TUGAS_BELAJAR', 'Tugas Belajar'), ('IZIN_BELAJAR', 'Izin Belajar'), ('CLTN', 'CLTN'), ('PENSIUN', 'Pensiun'), ('MENINGGAL', 'Meninggal'), ('PINDAH', 'Pindah Instansi'), ('BERHENTI', 'Berhenti')], max_length=30)),
                ('jenis_cuti', models.CharField(blank=True, choices=[('TAHUNAN', 'Cuti Tahunan'), ('BESAR', 'Cuti Besar'), ('SAKIT', 'Cuti Sakit'), ('MELAHIRKAN', 'Cuti Melahirkan'), ('ALASAN_PENTING', 'Cuti Karena Alasan Penting'), ('DILUAR_TANGGUNGAN_NEGARA', 'Cuti di Luar Tanggungan Negara')], max_length=50, null=True)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_akhir', models.DateField(blank=True, null=True)),
                ('no_sk', models.CharField(blank=True, max_length=100)),
                ('dokumen_pendukung', models.URLField(blank=True, max_length=500, null=True, verbose_name='Dokumen Pendukung (Link)')),
                ('keterangan', models.TextField(blank=True)),
                ('tendik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_status', to='tendik.tendik')),
            ],
        ),
    ]
