# Generated by Django 5.2 on 2026-07-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0010_keluargadosen_riwayatstatustendik'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeluargaDosen',
            new_name='KeluargaTendik',
        ),
    ]
