# Generated by Django 4.2.30 on 2026-07-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendik', '0010_riwayatstatustendik_keluargatendik'),
        ('tendik', '0011_rename_keluargadosen_keluargatendik'),
    ]

    operations = [
    ]
